### ISSUE TITLE
no-js tab switcher

### ISSUE THREAD

**Issue by coolaj86** [BeyondCodeBootcamp/mvp.html#3]
Re: https://stackoverflow.com/a/71008554

```css
dialog { display: block; }

dialog:not(:target):not([open]) { display: none; }
```

```html
<html>
  <body>
      <p>
        <a href="#dialog">Open dialog</a>
      </p>

      <dialog id="dialog">
        <h2>Dialog</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        <a href="#!">Close</a>
      </dialog>
  </body>
</html>
```

Not sure if this would have to enumerate every hash target (ex: `#main`, `#settings`) or if this could be done by some sort of dynamic class selector, but this should allow tabs without JavaScript.
